In [1]:
import numpy as np

In [8]:
matrix = np.full((3,3), fill_value = 11)
print(matrix)

[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [2]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.eye(5,5,-3)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [14]:
np.eye(4,4,0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.randint(1,10)

4

In [18]:
array = (1, 2, 3, 4)

In [23]:
dimension = array.ndim

AttributeError: 'tuple' object has no attribute 'ndim'

In [24]:
list =5

In [25]:
list((1,2,3,4))

TypeError: 'int' object is not callable

In [26]:
np.ones

<function numpy.ones(shape, dtype=None, order='C', *, like=None)>

# shape

In [36]:
a = np.array(((1, 2, 3), (1, 2, 3)))

In [32]:
row,col = a.shape

print(f'no of rows: {row}\nNo of columns: {col}')

no of rows: 2
No of columns: 3


In [31]:
print(a,)

[[1 2 3]
 [1 2 3]]


# size

In [39]:
a = np.array(((1, 2, 3),(2, 3, 4),(1, 2, 3),(2,3,4)))
a

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4]])

In [40]:
a.size

12

In [41]:
size = a.size
print(f'no of rows: {row}\nNo of columns: {col}')
print(f'Size od array: {size}')

no of rows: 2
No of columns: 3
Size od array: 12


# DTYPE

In [4]:
import numpy as np

WEIGHT_AGE = np.array([(3.3, 4.2, 5.7), (1, 0.3, 0.8)])
print("dtype of elements in array is ", WEIGHT_AGE.dtype)

dtype of elements in array is  float64


In [ ]:
import matplotlib.pyplot

In [11]:
ar = ([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
b = ar.reshape(2,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
b[1][1:3]

array([7, 8])

In [17]:
b[0][-3:]

array([3, 4, 5])